config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'

  get '/action_cable_test' => 'application#action_cable_test'
  post '/action_cable_test_broadcast' => 'application#action_cable_test_broadcast'

  get '/welcome' => 'application#welcome', as: :application_welcome

  get '/events/add' => 'events#add', as: :events_add
  post '/events/add' => 'events#add', as: :events_add_post
  get '/events(/:event_time)' => 'events#index', as: :events_index

  get '/hosts/register' => 'hosts#register', as: :hosts_register
  post '/hosts/register' => 'hosts#register', as: :hosts_register_post
  get '/hosts/login' => 'hosts#login', as: :hosts_login
  post '/hosts/login' => 'hosts#login', as: :hosts_login_post
  get '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile
  post '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile_post
  get '/hosts/logout' => 'hosts#logout', as: :hosts_logout

  get '/users/register' => 'users#register', as: :users_register
  post '/users/register' => 'users#register', as: :users_register_post
  get '/users/login' => 'users#login', as: :users_login
  post '/users/login' => 'users#login', as: :users_login_post
  get '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile
  post '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile_post
  get '/users/logout' => 'users#logout', as: :users_logout
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authorize, :except => [:welcome]

  def action_cable_test

  end

  def action_cable_test_broadcast
    ActionCable.server.broadcast 'rs_control', {
      type: 'RS-Test-Message',
      message: 'If you see this, Action Cable works!'
    }
  end

  def current_user
    if session[:account_type]
      @account_type = session[:account_type]
      if session[:account_type] == 'user'
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      else
        @current_host ||= Host.find(session[:host_id]) if session[:host_id]
      end
    end
  end

  def authorize
    redirect_to application_welcome_path unless current_user
  end

  def only_host_action
    redirect_to events_index_path unless session[:account_type] == 'host'
  end

  def welcome

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/action_cable_test.html.erb
<div id="test_holder" class="events index">
  <h3>ACTION CABLE TEST</h3>
  <br/>
  <div><button id="ac_test_btn">Test</button></div>
  <br/>
  <div id="message_holder">Click Above To Test.</div>
</div>
<script>
  $('#test_holder').action_cable_test_control({
    test_btn_id: '#ac_test_btn',
    message_holder_id: '#message_holder'
  });
</script>

app/views/application/welcome.html.erb
<div class="loginForm">
  <h2>Select your account type </h2>
  <ul>
    <li>
      <h4><%= link_to "Normal User", users_login_path %></h4>
    </li>
    <br/>
    <li>
      <h4><%= link_to "Host", hosts_login_path %></h4>
    </li>
  </ul>
</div>